# Generated by Django 6.1 on 2026-08-22 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('fhir_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('identifier_system', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier_value', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('family_name', models.CharField(blank=True, max_length=200, null=True)),
                ('given_name', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=400, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('migrated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fhir_id'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('fhir_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='unknown', max_length=30)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('code_system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('code_display', models.CharField(blank=True, max_length=255, null=True)),
                ('code_text', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('value_system', models.CharField(blank=True, max_length=255, null=True)),
                ('value_code', models.CharField(blank=True, max_length=50, null=True)),
                ('migrated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='api.patient')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
