# Generated by Django 6.1 on 2026-08-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='fhir_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fhir_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
