# Generated by Django 6.1 on 2026-08-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_widen_observation_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=20)),
                ('patients_offset', models.PositiveIntegerField(default=0)),
                ('patients_written', models.PositiveIntegerField(default=0)),
                ('patients_skipped', models.PositiveIntegerField(default=0)),
                ('observations_written', models.PositiveIntegerField(default=0)),
                ('observations_skipped', models.PositiveIntegerField(default=0)),
                ('expected_patients', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_observations', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'get_latest_by': 'started_at',
            },
        ),
    ]
